services:
  proxy:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
    networks:
      - drawguess-net

  backend:
    build: ./backend
    expose:
      - "5000"
    networks:
      - drawguess-net

  frontend:
    build: ./my-app
    expose:
      - "3000"
    depends_on:
      - backend
    networks:
      - drawguess-net

networks:
  drawguess-net:
    driver: bridge
